services:

  shredder:
    image: brocker591/shredder
    container_name: shredder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Data Source=Data/shredderDB
    volumes:
      - shredder_data:/app/Data
    ports:
      - 8888:80

volumes:
  shredder_data:
